# Generated by Django 5.1.4 on 2025-01-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dream',
            name='title',
        ),
        migrations.AlterField(
            model_name='dream',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
